### lists all messages
GET http://localhost:3000/messages

### create new message
POST http://localhost:3000/messages
content-type: application/json

{
    "content": "AFTER DI" 
}

### GET a message
GET http://localhost:3000/messages/248